Pull request for strickler.
leonmezu1/Working-with-bootstrap-4-Microverse-Project pull request #1
Opened 2019-10-29 21:55 UTC by leonmezu1

2019-11-07 23:08 UTC, Anna-Myzukina commented
### Pull Request under the review by Anna Muzykina (TSE)

2019-11-07 23:19 UTC, Anna-Myzukina commented on index.html
> +				<span>SIGN IN</span><a href="#" id="subs">SUBSCRIBE <i class="fas fa-chevron-right" id="chevron"></i></a>
SIGN IN should be a link

2019-11-07 23:23 UTC, Anna-Myzukina commented on index.html
> +					</ul>
It should contain the main navigation links.

2019-11-07 23:25 UTC, Anna-Myzukina commented on index.html
> +							<li class="last li-item">România</li>
It should be links

2019-11-08 03:59 UTC, Redvanisation requested changes
# Changes required  🛑

### Hello @leonmezu1   🌟

**Good work implementing the changes, but we need to fix some more issues before moving on ⬇️** 

1. Please implement all the changes required in the previous review before submitting again.

2. Please delete the unnecessary files and folders from the repo (e.g: `.vscode` folder, and all the JavaScript files).

3. Set up Stickler to lint the CSS on your project, find out more on how to do that in [here](https://github.com/microverseinc/linters-config/tree/master/css)

4. Please Validate and fix the HTML markup [here](https://validator.w3.org/#validate_by_input)

5. Make the README file more descriptive, check [this](https://github.com/othneildrew/Best-README-Template) link for reference.

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

2019-11-08 06:48 UTC, leonmezu1 commented
Hi!
Thanks for your valuable reviews!

I managed to fix the most of the issues.
The Navbar and Footers elements now have an <a> parent where it was required.

I don't really know why stickler is taking eternities to load and check, I already uninstalled and reinstalled it with no positive result.
The JavaScript files in the repository are mainly to allow stickler work in VS Code, I also  created a script.js file which contains the rules for some Navbar elements.

Regarding the CSS file size, to my defense I can only argue that the Bootstrap classes have a prefixed size for margin and padding which didn't allowed me to position the elements in the desired place another thing is I'm using a Sass preprocessor just for adding compatibility across browser, maybe it's adding more lines than the expected.

2019-11-08 07:20 UTC, ebukaume commented
## Changes Required! :stop_sign: 

Hi @leonmezu1 :wave: 

You have really done well so far. You are almost done but we can't move forward without making sure there are no lint errors (stickler-ci).

Please refer to [this guide](https://github.com/microverseinc/linters-config/tree/master/css#troubleshooting) to help you troubleshoot why stickler is not working for this repo.

While at it, you can make your README to be more professional. Use [this template](https://github.com/othneildrew/Best-README-Template) as inspiration.

[SIDE NOTE]
Finally, as a note, you really wrote too much SCSS. You could easily achieve most of those styling with bootstrap classes.

**Please submit another code review request after fixing the above issues**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

2019-11-08 20:15 UTC, leonmezu1 commented
Again **thanks a lot** for your valuable reviews.

After fighting some hours with Stickler I managed to fix the whole problem it was due to the commit verification settings.
Now the Linter is working and the code is error free.

I updated the README.md file so it looks better and it's more descriptive now. 
Also, I checked the CSS sheet to shrink styling deleting more than 80 lines of unnecessary code.

Looking forward the new code review 👀

2019-11-08 20:22 UTC, ebukaume commented
## Approved! :champagne: 

Hi @leonmezu1 :wave: 

You have really done well. I like your dedication. **You are approved to merge this branch.**


Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

2019-11-08 20:37 UTC, merged